version: '2'

services:
    safepass:
        build: .
        image: josaorg/safepass
        ports:
            - "5000:5000"
        stop_signal: SIGINT
        environment:
            - MATOMO_SITE_ID=14
            - MATOMO_URL=https://track.josa.ngo/
            - REDIS_HOST=redis
            - ONION_ADDRESS=http://xlaci2kx3vivuhngpynpkjbmlqrgdoqvncyziekev2stndktr52nf4yd.onion
            - NO_SSL=True
        depends_on:
            - redis
    redis:
        image: "redis:latest"
        # ports:    # uncomment for debugging
            # - "6379:6379"
