services:
  safepass:
    build: .
    image: josaorg/safepass
    ports:
      - '5000:5000'
    stop_signal: SIGINT
    env_file: env/.env
    depends_on:
      - redis

  redis:
    image: 'redis:latest'
